#!/usr/bin/env python3

import sys, os

# disable cache usage must be before any local imports
sys.dont_write_bytecode = True

from functools import partial

from PyQt6.QtCore import QTimer
from PyQt6.QtWidgets import QApplication, QMainWindow
from PyQt6.uic import loadUi

import linuxcnc as emc
import hal

from libtestgui import readini
from libtestgui import startup
from libtestgui import status
from libtestgui import utilities

class testgui(QMainWindow):
	def __init__(self):
		super().__init__()

		if os.path.isdir('/usr/lib/libtestgui'):
			self.lib_path = '/usr/lib/libflexgui'

		for i in range(len(sys.argv)): # check if running from ini DISPLAY entry
			if sys.argv[i].endswith('.ini'):
				# self.ini_path path to ini file
				self.ini_path = sys.argv[i]
				self.inifile = emc.ini(sys.argv[i])
				# self.config_path path to configuration
				self.config_path = os.path.split(sys.argv[i])[0]
				break
		else: # no match was found
			msg = ('Test GUI must be called from\n'
			'the LinuxCNC ini file.')
			dialogs.error_msg_ok(self, msg, 'Error')
			sys.exit()

		# connect to linuxcnc
		self.status = emc.stat()
		self.status.poll()
		self.command = emc.command()
		self.error = emc.error_channel()

		# setup hal components
		self.halcomp = hal.component('flexhal')

		# find and load the gui
		gui_file = self.inifile.find('DISPLAY', 'GUI') or False
		if gui_file: # gui is in the ini file
			gui_path = os.path.join(os.path.dirname(self.status.ini_filename), gui_file)
			loadUi(gui_path, self)

		# read the ini settings
		readini.read(self)

		# check for a resources.py file with images for the stylesheet
		if self.resources_file: # import the resources file
			try:
				sys.path.append(self.config_path)
				import resources
			except:
				msg = (f'The resources file {resources_file} was\n'
					'not found, check for file name resources.py.')
				dialogs.warn_msg_ok(parent, msg, 'Import Failed')

		if self.qss_file: # use a local qss file
			stylesheet = os.path.join(self.config_path, self.qss_file)
			if os.path.isfile(stylesheet):
				with open(stylesheet, 'r') as f:
					self.setStyleSheet(f.read())
			else:
				msg = (f'The Stylesheet {stylesheet}\n'
					'was not found.')
				dialogs.warn_msg_ok(parent, msg, 'INI Error')

		# set emc states to -0 so they get evaluated in status at least once
		self.exec_state = -0
		self.interp_state = -0
		self.interpreter_errcode = -0
		self.motion_mode = -0
		self.motion_type = -0
		self.state = -0
		self.task_mode = -0
		self.task_state = -0
		self.file = -0
		self.flood_state = -0
		self.mist_state = -0

		startup.find_children(self)
		startup.setup_vars(self)
		startup.setup_status(self)
		startup.setup_enables(self)
		startup.setup_run_controls(self)
		startup.setup_buttons(self)
		startup.setup_actions(self)
		startup.setup_mdi(self)
		startup.setup_mdi_buttons(self)
		startup.setup_jog(self)
		startup.setup_plot(self)
		startup.setup_hal(self)
		startup.setup_plain_text_edits(self)
		startup.setup_probing(self)


		startup.setup_defaults(self)

		# setup and start the status update timer every 0.01 second
		self.update_timer = QTimer()
		self.update_timer.timeout.connect(partial(status.update, self))
		self.update_timer.start(self.cycle_time) # milliseconds

		# setup the i/o watch timer
		self.io_watch_timer = QTimer(self)
		self.io_watch_timer.timeout.connect(partial(utilities.io_watch, self))
		self.io_watch_timer.start(1000) # milliseconds

		# set the screen size and position
		if self.settings.contains('GUI/window_size'):
			self.resize(self.settings.value('GUI/window_size'))
		if self.settings.contains('GUI/window_position'):
			self.move(self.settings.value('GUI/window_position'))
		else:
			self.move(0, 0) # if no settings move window to upper left corner

		self.show()

	def closeEvent(self, event):
		self.settings.setValue('GUI/window_size', self.size())
		self.settings.setValue('GUI/window_position', self.pos())
		#if self.help_dialog is not None:
		#	self.help_dialog.close()


app = QApplication(sys.argv)
window = testgui()
sys.exit(app.exec())

